### ISSUE TITLE
Object handling

### ISSUE THREAD

**Issue by Taucher2003** [code0-tech/tucana#21]
> As this is merged, but not finished we need to keep this issue or need to create a separate one to discuss the handling of `OBJECTS`  

 _Originally posted by @nicosammito in [#10](https://github.com/code0-tech/tucana/issues/10#issuecomment-2500910759)_

**Comment by nicosammito** [comment]
because everything is planned in https://github.com/code0-tech/pictor/issues/233 we can close this for now
